name       : python-pyotherside
version    : 1.5.9
release    : 20
source     :
    - https://github.com/thp/pyotherside/archive/1.5.9.tar.gz : 189cb0b973e40fcb6b95fd51b0bcd6cc8494b514d49ffe966ec488cf05bbf51e
license    : ISC
component  : programming.python
summary    : Asynchronous Python 3 Bindings for Qt 5
description: |
    A Qt 5 QML Plugin that provides access to a Python 3 interpreter from QML
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - xorg-server-xvfb
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    rm -r $installdir/usr/tests
check      : |
    xvfb-run ./tests/tests
