name       : python-pyotherside
version    : 1.6.0
release    : 24
source     :
    - https://github.com/thp/pyotherside/archive/1.6.0.tar.gz : ead71d0a549acb6664d72745fae5b1d4e433274c64be6a680ceeeef0754451ab
license    : ISC
component  : programming.python
summary    : Asynchronous Python 3 Bindings for Qt 5
description: |
    A Qt 5 QML Plugin that provides access to a Python 3 interpreter from QML
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(python3)
    - xorg-server-xvfb
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    rm -r $installdir/usr/tests
check      : |
    xvfb-run ./tests/tests
