name       : python-pyotherside
version    : 1.5.1
release    : 7
source     :
    - https://github.com/thp/pyotherside/archive/1.5.1.tar.gz : cb29853d66d2e33f68e28c62c28d054512ab82a763fed8b7b7df9dae722c5de2
license    : ISC
component  : programming.python
summary    : Asynchronous Python 3 Bindings for Qt 5
description: |
    Asynchronous Python 3 Bindings for Qt 5
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(python3)
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    rm -r $installdir/usr/tests
