name       : python-pyotherside
version    : 1.5.3
release    : 10
source     :
    - https://github.com/thp/pyotherside/archive/1.5.3.tar.gz : 00049d5f42cac448368bc2a521edb8de36bb6d2a624e195b7f1004236758b805
license    : ISC
component  : programming.python
summary    : Asynchronous Python 3 Bindings for Qt 5
description: |
    A Qt 5 QML Plugin that provides access to a Python 3 interpreter from QML
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(python3)
    - xorg-server-xvfb
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    rm -r $installdir/usr/tests
check      : |
    xvfb-run ./tests/tests
