name       : python-pyotherside
version    : 1.5.8
release    : 13
source     :
    - https://github.com/thp/pyotherside/archive/1.5.8.tar.gz : 7e4ba2b601eb2d67618e0355cc249ed7d2555940af24f84bb4cbf31eb7df7808
license    : ISC
component  : programming.python
summary    : Asynchronous Python 3 Bindings for Qt 5
description: |
    A Qt 5 QML Plugin that provides access to a Python 3 interpreter from QML
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(python3)
    - xorg-server-xvfb
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    rm -r $installdir/usr/tests
check      : |
    xvfb-run ./tests/tests
